"""empty message

Revision ID: 89d71bf80031
Revises: 7e52ff876018
Create Date: 2021-03-12 13:20:38.128483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d71bf80031'
down_revision = '7e52ff876018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'created_at')
    # ### end Alembic commands ###
