"""empty message

Revision ID: 7e52ff876018
Revises: 40158da03c1d
Create Date: 2021-03-06 17:59:32.431457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e52ff876018'
down_revision = '40158da03c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('practice_logs_date_key', 'practice_logs', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('practice_logs_date_key', 'practice_logs', ['date'])
    # ### end Alembic commands ###
